Traceback (most recent call last):
  File "169_redirction_stdinouterror.py", line 20, in <module>
    print sys.argv[1]
IndexError: list index out of range
